title: "Serena Bonaretti"
author: "Serena Bonaretti"
description: "Personal Webpage"
more: "read more »"
url: "https://sbonaretti.github.io"
#baseurl: "/contrast" # comment out if in root directory
baseurl: "/"

comments:
  disqus: "niklasbuschmann"
#  isso: "comments.mysite.org"

style:
  body: 'white' # main background color
  padding: 3 # factor for the padding width
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  nav: "#222" # color of the header and footer
  uppercase: true # use uppercase text for headings
  margin: 0% # increase to add a margin to the left and right side
  margincolor: "#f0f0f0" # only relevant if margin is non-zero

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/me/", square: true}
  - reddit: {url: "https://www.reddit.com/user/me/", square: true}
  - twitter: {url: "https://twitter.com/me/", square: true}
  - facebook: {url: "https://www.facebook.com/me", square: true}
  - google-plus: {url: "https://plus.google.com/+me", square: true}
  - youtube: {url: "https://www.youtube.com/user/me", square: true}
  - tumblr: {url: "http://me.tumblr.com/", square: true}
  - steam: {url: "http://steamcommunity.com/id/me/", square: true}

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
